on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

name: Git flow

jobs:
  apply:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_at != null
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: develop
          fetch-depth: 0

      - name: Apply git flow
        run: |
          echo "Setting up credentials"
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "Fetching 'main'"
          git fetch origin main:main --progress
          echo "Merging 'main'"
          git merge main
          echo "Deleting branch '${{ github.event.pull_request.head.ref }}'"
          git push origin --delete ${{ github.event.pull_request.head.ref }}
          echo "Updating 'develop'"
          git push origin develop
