on:
  pull_request:
    branches: [ main, develop ]
    types: [ closed ]

name: Git Flow

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_at != null && github.event.pull_request.base.ref == 'main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: develop
          fetch-depth: 0

      - name: Preparing
        run: |
          echo "Fetching 'main'"
          git fetch origin main:main --progress
          
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GIT_FLOW_ACCESS_KEY }}

      - name: Merging main into develop
        run: |
          echo "Merging 'main' into 'develop'"
          git merge main
          echo "Pushing 'develop'"
          git push
#          ORIGIN=https://${{ secrets.GIT_FLOW_ACCESS_KEY }}@github.com/${{ github.repository }}
#          git push $ORIGIN develop

  close-branch:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged_at != null
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
          
      - name: Configure git credentials
        uses: OleksiyRudenko/gha-git-credentials@v1
        with:
          token: ${{ secrets.GIT_FLOW_ACCESS_KEY }}

      - name: Delete remote branch
        run: |
          BRANCH=${{ github.event.pull_request.head.ref }}
          USER="${{ secrets.GIT_FLOW_USER_NAME }}:${{ secrets.GIT_FLOW_ACCESS_KEY }}"
          ORIGIN=https://$USER@github.com/${{ github.repository }}
          git ls-remote --exit-code --heads $ORIGIN $BRANCH
          if [ $? -eq 0 ]; then \
            echo "Deleting branch '$BRANCH'"; \
            git push origin --delete $BRANCH; \
          else \
            echo "ref/heads/$BRANCH does not exists on remote"; \
          fi
