on:
  pull_request:
    branches: [ develop ]
    types: [ synchronize ]

name: Tests

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        
      - name: Setup PostgreSQL
        # You may pin to the exact commit or the version.
        # uses: Harmon758/postgresql-action@0be19fa37850b22cb4c9bbf28a03abbf44abd863
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 11
          postgresql db: gw_testing
          postgresql user: gdoorweb
          postgresql password: postgres
          
      - run: php -v
